app:
  name: cli
http:
  mode: release
  port: 8080
log:
  filename: cli.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
consul:
  addr: 127.0.0.1:8500
grpc:
  port: 0
jaeger:
  serviceName: cli
  reporter:
    localAgentHostPort: "127.0.0.1:6831"
  sampler:
    type: const
    param: 1
