app:
  name: files
http:
  mode: debug
  port: 8888
log:
  filename: logs/files.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
consul:
  addr: consul:8500
grpc:
  port: 0
jaeger:
  serviceName: files
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
files:
  type: local
  base: test_files
