app:
  name: server
http:
  mode: debug
  port: 8888
log:
  filename: logs/server.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
consul:
  addr: consul:8500
grpc:
  port: 0
jaeger:
  serviceName: server
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1